"""
Génère le PDF de publication défensive pour claude-cognition.
Utilise le même process que gen_defensive_pdf.py (2026-05-04).
"""
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

TITLE = "Claude Cognition: Persistent 3-Layer Cognitive Memory Graph for Claude Code"
AUTHORS = "Stadelmann, Sébastien"
DATE = datetime.now().strftime("%Y-%m-%d")
ABSTRACT = """
Claude Cognition is an open-source Python package implementing a persistent 3-layer
cognitive memory graph for Claude Code (Anthropic). The system addresses the universal
problem of session amnesia in large language model interactions: every session starts
from zero, requiring users to re-explain context, past decisions, and constraints.

Architecture:
1. Episodic Layer — stores events, decisions with their reasoning, and outcomes,
   indexed by project and timestamp.
2. Semantic Layer — stores persistent facts about the user, their stack, and domain
   knowledge as key-value pairs with confidence scores.
3. Procedural Layer — stores validated workflows, patterns, and heuristics discovered
   during prior sessions.

Additionally, a Temporal Guard Layer detects when a current user action matches a
previously recorded negative pattern (an action that led to an undesirable outcome),
issuing a proactive warning before the error is repeated.

Integration with Claude Code is achieved through the native hook system:
- SessionStart hook: the `cognition inject` command generates a ranked, keyword-scored
  context block from all 3 layers, which Claude Code injects automatically into the
  new session's context.
- Stop hook: the `cognition auto-capture` command snapshots the current project state
  (git log, recent changes) and increments the session counter.

The system requires no external dependencies (pure Python stdlib), operates fully
offline, and stores all data locally in ~/.cognition/ as human-readable JSON and
Markdown files.

This publication establishes prior art for the architecture of:
(a) a multi-layer cognitive graph for LLM session memory,
(b) temporal pattern detection with negative pattern guards in LLM assistants,
(c) automatic bidirectional memory injection via native hook systems in AI coding tools.
"""

KEYWORDS = [
    "claude code", "persistent memory", "cognitive graph", "llm memory",
    "session continuity", "temporal pattern detection", "ai coding assistant",
    "hook system", "episodic memory", "procedural memory", "prior art"
]


def generate_markdown():
    md = f"""# {TITLE}

**Authors:** {AUTHORS}
**Date:** {DATE}
**Repository:** https://github.com/bes1705/claude-cognition
**License:** MIT

## Abstract
{ABSTRACT.strip()}

## Keywords
{', '.join(KEYWORDS)}

## System Architecture

### Layer 1 — Episodic Memory
Stores timestamped events with the format:
```json
{{"content": "[DECISION] chose Redis over Postgres — latency < 10ms",
  "project": "my-project", "tags": ["decision"], "ts": "2026-05-05T..."}}
```

### Layer 2 — Semantic Memory
Persistent facts as key-value pairs:
```json
{{"stack": {{"value": "FastAPI + React + Postgres", "confidence": 0.95}}}}
```

### Layer 3 — Procedural Memory
Validated patterns and workflows:
```json
{{"pattern": "always run tests before pushing — prevents prod breakage",
  "project": "my-project", "tags": ["testing"]}}
```

### Temporal Guard Layer
Negative pattern detection via keyword overlap scoring:
- Compares current user action against all stored negative patterns
- Fires a warning when keyword overlap ≥ 50%
- Tracks hit count to identify repeatedly dangerous patterns

## Installation
```bash
git clone https://github.com/bes1705/claude-cognition
cd claude-cognition
python install.py
```

## CLI Interface
```
cognition save --type decision "chose X over Y because Z"
cognition save --type avoid "never do X without Y"
cognition recall "trading"
cognition detect "I'm about to modify production config"
cognition inject    # SessionStart hook
cognition auto-capture  # Stop hook
cognition status
```

## Prior Art Declaration
This document establishes prior art as of {DATE} for the described architecture.
No patent protection is sought. The goal is to prevent third parties from obtaining
patent protection on these techniques, keeping them freely available to all.

---
*Generated by JARVIS — {DATE}*
"""
    return md


def main():
    out_dir = Path.home()
    md_path = out_dir / "defensive_publication_claude_cognition.md"
    md_path.write_text(generate_markdown(), encoding="utf-8")
    print(f"[OK] Markdown: {md_path}")

    # Try to generate PDF via weasyprint or fallback to markdown only
    pdf_path = out_dir / "defensive_publication_claude_cognition.pdf"
    try:
        from weasyprint import HTML
        HTML(string=f"<pre>{generate_markdown()}</pre>").write_pdf(str(pdf_path))
        print(f"[OK] PDF: {pdf_path}")
    except ImportError:
        print(f"[INFO] weasyprint not installed — markdown only at {md_path}")
        print(f"[INFO] To generate PDF: pip install weasyprint && python {__file__}")

    print(f"\n[NEXT] Upload to Zenodo: https://zenodo.org/uploads/new")
    print(f"       Title    : {TITLE}")
    print(f"       Keywords : {', '.join(KEYWORDS[:5])}")


if __name__ == "__main__":
    main()
